server:
  port: 9000
  address: 0.0.0.0
  undertow:
    io-threads: 16
    worker-threads: 4000
    buffer-size: 1024
    direct-buffers: true
  compression:
    enabled: true
    min-response-size: 1

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ai?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true&tinyInt1isBit=false
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    cors:
      allowed-origins:
        - http://192.168.78.103:5173
        - file://
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600
  mail:
    host: smtp.qq.com
    username: 2902756263@qq.com
    password: euvqajvjrpnndgda
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
  jvm:
    args: --add-opens java.base/java.lang.invoke=ALL-UNNAMED
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.advisor.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_uuid
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

jwt:
  secret: your_jwt_secret_key_here_should_be_very_long_and_secure_12345678901234567890
  expiration: 86400000 # 24小时，单位毫秒

# 七牛云配置
qiniu:
  access-key: 94BvdJExQ963UsZRcc2rMNoIfoZb1-1CfCrsjoEg
  secret-key: 3Bpbjy6Cn68P9Sglbm4KSv32MgzJuFEbUqXzmulx
  bucket: myai-resource
  domain: http://su5mwlhe1.hb-bkt.clouddn.com

dashscope:
  api-key: sk-52fed3345ebb41d3bb0c003d79d7cca9

# 语音识别配置
voice:
  recognition:
    enabled: true
    max-size: 20971520 # 20MB，语音文件最大大小
    upload-dir: voice/ # 七牛云存储中的目录

# 聊天机器人API配置
chatbot:
  api:
    url: http://localhost:5000

# AI服务配置
agent:
  api:
    url: http://localhost:5000

emotion:
  recognition:
    api:
      url: http://localhost:5000

baidu:
  aip:
    app-id: 118009849
    api-key: 1V9jO3svJBx3MCEGvQaPYFhm
    secret-key: i6M1PmXsAymBrYmNS0YokxZM1dmroikT
